#!/usr/bin/bash
#
# Usage: xupdman <file>
#
#   where <file> is a file (from TSRchitect/R/*R) with updated roxygen header

Rfile=$1

# ... roxygenized the TSRchitect package and install the package
#     (use sudo to install system-wide):
#

Rscript -e "roxygen2::roxygenize()"
cd ..
sudo R CMD INSTALL TSRchitect
cd TSRchitect

# ... now display the updated man page:
#
Rscript -e "library(TSRchitect); ?$Rfile"
