### Note: Before you run this demo, please copy the contents of /DATA/TSRchitect-demo/RAMPAGE into extdata/RAMPAGE.
###       Then run "Rscript demo-CAGE.R" from within TSRchitect.
####################################################################################################

# ... installing TSRchitect from source:
#devtools::install_github("brendelgroup/TSRchitect")

# ... loading the TSRchitect library:
library(TSRchitect)

# ... initializing the tssObj object:
initializeExp("Example human CAGE experiment", "CAGEhuman", c("extdata/CAGE"), isPairedEnd=FALSE) #

# ... setting the sample IDs and names for the datasets within the CAGE library
setSampleID(CAGEhuman, c("Example_1"), 1)

# ... loading the BAM files from the TSS profiling experiment (in this case, CAGE):
importBam(CAGEhuman)

# ... converting BAM data into TSS information and attaching it to the tssObj object:
bamToTSS(CAGEhuman)

# ... constructing the tag count per TSS data matrix:
CAGEhuman@tssCountData[[1]] <- processTSS(experimentName=CAGEhuman, tssSet=1, writeTable=FALSE)

# ... finding TSRs for the given dataset:
findTSR(experimentName=CAGEhuman, setToCluster="replicates", tssSet=1, nTSSs=5, clustDist=20, writeTable=FALSE)


# ... uncomment the following line if you would like to the data generated by the above
#     for future reloading with the R load command:
#save(riceRAMPAGE, file="demo-CAGE-test.RData")
