### Note: Before you run this demo, please copy five bam alignment files into BAMDIR under TSRchitect.
###       Then run "Rscript demo-RAMPAGE.R" from within TSRchitect.
####################################################################################################

# ... installing TSRchitect from source:
#devtools::install_github("brendelgroup/TSRchitect")

# ... loading the TSRchitect library:
library(TSRchitect)

# ... initializing the tssObj object:
initializeExp("Example RAMPAGE experiment (Rice)", "riceRAMPAGE", "BAMDIR", isPairedEnd=TRUE)

# ... setting the sample IDs and names for the datasets within the RAMPAGE library:
setSampleID(riceRAMPAGE, c("DL1_1","DL1_2", "DL2_1", "DL2_2", "DL2_3"), c(1,1,2,2,2))

# ... loading the BAM files from the TSS profiling experiment (in this case, RAMPAGE):
importBam(riceRAMPAGE)

# ... converting BAM data into TSS information and attaching it to the tssObj object:
bamToTSS(riceRAMPAGE)

# ... constructing the tag count per TSS data matrices:
for (i in 1:5) {
  riceRAMPAGE@tssCountData[[i]] <- processTSS(experimentName=riceRAMPAGE, tssSet=i, writeTable=TRUE)
}

# ... finding TSRs for all data sets (here 5):
for (i in 1:5) {
  riceRAMPAGE@tsrData[[i]] <- findTSR(experimentName=riceRAMPAGE, setToCluster="replicates", tssSet=i, tagCountThreshold=3, clustDist=20, writeTable=TRUE)
}

# ... now merging tssCountData lists according to the replicate info:
mergeSampleData(experimentName=riceRAMPAGE)

# ... now identifying TSRs from the merged datasets (here control [i=1] and condition [i=2]) and the combined set [i=3]:
for (i in 1:3) {
  riceRAMPAGE@tsrDataMerged[[i]] <- findTSR(experimentName=riceRAMPAGE, setToCluster="merged", tssSet=i, tagCountThreshold=3, clustDist=20, writeTable=TRUE)
}

# ... now adding tag count output:
#
system.time(  determineTSR(experimentName = mytestM, setToCluster="combined", tagCountThreshold=10, clustDist=20, writeTable = TRUE)  )


# ... uncomment the following line if you would like to the data generated by the above
#     for future reloading with the R load command:
#save(riceRAMPAGE, file="demo-RAMPAGE-test.RData")
