### Note: Before you run this demo, please copy five bam alignment files into BAMDIR under TSRchitect.
###       Then run "Rscript demo-RAMPAGE.R" from within TSRchitect.
####################################################################################################

# ... installing TSRchitect from source:
#devtools::install_github("brendelgroup/TSRchitect")

# ... loading the TSRchitect library:
library(TSRchitect)

# ... initializing the tssObj object:
initializeExp("Example RAMPAGE experiment (Rice)", "riceRAMPAGE", "BAMDIR", isPairedEnd=TRUE)

# ... setting the sample IDs and names for the datasets within the RAMPAGE library:
setSampleID(riceRAMPAGE, c("DL1_1","DL1_2", "DL2_1", "DL2_2", "DL2_3"), c(1,1,2,2,2))

# ... loading the BAM files from the TSS profiling experiment (in this case, RAMPAGE):
importBam(riceRAMPAGE)

# ... converting BAM data into TSS information and attaching it to the tssObj object:
bamToTSS(riceRAMPAGE)

# ... constructing the tag count per TSS data matrix:
processTSS(experimentName=riceRAMPAGE, tssSet=1, writeTable=TRUE)
processTSS(experimentName=riceRAMPAGE, tssSet=2, writeTable=TRUE)
processTSS(experimentName=riceRAMPAGE, tssSet=3, writeTable=TRUE)
processTSS(experimentName=riceRAMPAGE, tssSet=4, writeTable=TRUE)
processTSS(experimentName=riceRAMPAGE, tssSet=5, writeTable=TRUE)

# ... finding TSRs for the given dataset:
tsrFind(experimentName=riceRAMPAGE, tssSet=1, tagCountThreshold=3, clustDist=20, setToCluster="replicates", writeTable=TRUE)
tsrFind(experimentName=riceRAMPAGE, tssSet=2, tagCountThreshold=3, clustDist=20, setToCluster="replicates", writeTable=TRUE)
tsrFind(experimentName=riceRAMPAGE, tssSet=3, tagCountThreshold=3, clustDist=20, setToCluster="replicates", writeTable=TRUE)
tsrFind(experimentName=riceRAMPAGE, tssSet=4, tagCountThreshold=3, clustDist=20, setToCluster="replicates", writeTable=TRUE)
tsrFind(experimentName=riceRAMPAGE, tssSet=5, tagCountThreshold=3, clustDist=20, setToCluster="replicates", writeTable=TRUE)

# ... now merging tssCountData lists according to the replicate info:
mergeSampleData(experimentName=riceRAMPAGE)

# ... now identifying TSRs from the merged datasets:
tsrFind(experimentName=riceRAMPAGE, tssSet=1, tagCountThreshold=3, clustDist=20, setToCluster="merged", writeTable=TRUE)


# ... uncomment the following line if you would like to the data generated by the above
#     for future reloading with the R load command:
#save(riceRAMPAGE, file="demo-RAMPAGE-test.RData")
