#!/bin/bash


# Preparatory steps:
#
mkdir downloads

echo "Sys.setenv("R_USER_CACHE_DIR"=\"${PWD}/tmpRcache\")" > demo1a.Rscript
echo 'library(ENCODExplorer)' >> demo1a.Rscript
echo 'encode_df <- get_encode_df()' >> demo1a.Rscript
echo 'cage_data <- fuzzySearch(searchTerm=c("ENCFF552BXH","ENCFF288VTZ","ENCFF265RSX", "ENCFF944PCJ"), database=encode_df,filterVector=c("file_accession"), multipleTerm=TRUE)' >> demo3a.Rscript
echo 'downloadEncode(cage_data, df=encode_df, format="bam")' >> demo3a.Rscript

Rscript demo3a.Rscript

mv *.bam downloads

mkdir HsCAGEbam
cd HsCAGEbam
ln -s ../downloads/ENCFF265RSX.bam A549-rep1.bam
ln -s ../downloads/ENCFF944PCJ.bam A549-rep2.bam
ln -s ../downloads/ENCFF552BXH.bam MCF7-rep1.bam
ln -s ../downloads/ENCFF288VTZ.bam MCF7-rep2.bam
cd ..


# Running the TSRchitect workflow:
#
echo 'library(TSRchitect)' >> demo3b.Rscript

echo '# initializing the tssObject, setting the sample IDs and importing the CAGE data' >> demo3b.Rscript
echo 'CAGEhuman <- loadTSSobj(experimentTitle ="Human CAGE", inputDir="HsCAGEbam", isPairedBAM=FALSE, sampleNames=c("A549-rep1","A549-rep2", "MCF7-rep1","MCF7-rep2"), replicateIDs=c(1,1,2,2) )' >> demo3b.Rscript

echo 'CAGEhuman <- inputToTSS(experimentName=CAGEhuman)' >> demo3b.Rscript

echo 'CAGEhuman <- processTSS(experimentName=CAGEhuman, n.cores=4, tssSet="all", writeTable=TRUE)' >> demo3b.Rscript

echo 'CAGEhuman <- determineTSR(experimentName=CAGEhuman, n.cores=4, tssSetType="replicates", tssSet="all", tagCountThreshold=25, clustDist=20, writeTable=TRUE)' >> demo3b.Rscript

echo 'CAGEhuman <- mergeSampleData(experimentName=CAGEhuman, n.cores=4, tagCountThreshold=25) ' >> demo3b.Rscript

echo 'CAGEhuman <- determineTSR(experimentName=CAGEhuman, n.cores=4, tssSetType="merged", tssSet="all", tagCountThreshold=40, clustDist=20, writeTable=TRUE)' >> demo3b.Rscript

echo 'CAGEhuman <- addTagCountsToTSR(experimentName=CAGEhuman, tsrSetType="merged", tsrSet=3, tagCountThreshold=40, writeTable=TRUE)' >> demo3b.Rscript

echo 'CAGEhuman <- importAnnotationHub(experimentName=CAGEhuman, provider="gencode", annotType="gff3", species="human", annotID="AH49555")' >> demo3b.Rscript

echo 'CAGEhuman <- addAnnotationToTSR(experimentName=CAGEhuman, tsrSetType="merged", tsrSet=1, upstreamDist=1000, downstreamDist=200, feature="transcript", featureColumnID="ID", writeTable=TRUE)' >> demo3b.Rscript

echo 'CAGEhuman <- addAnnotationToTSR(experimentName=CAGEhuman, tsrSetType="merged", tsrSet=2, upstreamDist=1000, downstreamDist=200, feature="transcript", featureColumnID="ID", writeTable=TRUE)' >> demo3b.Rscript

echo 'CAGEhuman <- addAnnotationToTSR(experimentName=CAGEhuman, tsrSetType="merged", tsrSet=3, upstreamDist=1000, downstreamDist=200, feature="transcript", featureColumnID="ID", writeTable=TRUE)' >> demo3b.Rscript

echo 'getTSRdata(CAGEhuman, slotType="merged", slot=1) -> MCF7.tsrs' >> demo3b.Rscript
echo 'dim(MCF7.tsrs)' >> demo3b.Rscript

echo 'getTSRdata(CAGEhuman, slotType="merged", slot=2) -> A549.tsrs' >> demo3b.Rscript
echo 'dim(A549.tsrs)' >> demo3b.Rscript

echo 'getTSRdata(CAGEhuman, slotType="merged", slot=3) -> CAGEhuman.tsrs' >> demo3b.Rscript
echo 'dim(CAGEhuman.tsrs)' >> demo3b.Rscript
echo 'head(CAGEhuman.tsrs)' >> demo3b.Rscript

echo 'save(CAGEhuman, file="CAGEhuman-vignette.RData")' >> demo3b.Rscript


Rscript demo3b.Rscript
