setClass(Class="tssObject",
         representation(
             title = "character",
             fileNames = "character",
             dataType = "character",
             sampleNames = "character",
             replicateIDs = "numeric",
             geneAnnot = "GRanges",
             bamData = "list",
             tssTagData = "GRangesList",
             tssCountData = "list",
             tssCountDataMerged = "list",
             countsData = "data.frame",
             tsrData = "list",
             tsrDataMerged = "list",
             tsrCounts = "data.frame",
             consensusTSRs = "data.frame"
             ),
         prototype(
             title = NA_character_,
             fileNames = NA_character_,
             dataType = NA_character_,
             sampleNames = NA_character_,
             replicateIDs = vector("integer"),
             geneAnnot = GRanges(),
             bamData = list(),
             tssTagData = GRangesList(),
             tssCountData = list(),
             tssCountDataMerged = list(),
             countsData = data.frame(),
             tsrData = list(),
             tsrDataMerged = list(),
             tsrCounts = data.frame(),
             consensusTSRs = data.frame()
             ),
         )
