setClass(Class="tssObject",
         representation(
             title = "character",
             fileNames = "character",
             dataType = "character",
             sampleNames = "character",
             replicateIDs = "numeric",
             bamData = "list",
             tssData = "GRangesList",
             tssDataMerged = "GRangesList",
             expData = "list",
             expDataMerged = "list",
             countsData = "data.frame",
             tsrData = "list",
             tsrDataMerged = "list",
             tsrCounts = "data.frame",
             consensusTSRs = "data.frame"
             ),
         prototype(
             title = NA_character_,
             fileNames = NA_character_,
             dataType = NA_character_,
             sampleNames = NA_character_,
             replicateIDs = vector("integer"),
             bamData = list(),
             tssData = GRangesList(),
             tssDataMerged = GRangesList(),
             expData = list(),
             expDataMerged = list(),
             countsData = data.frame(),
             tsrData = list(),
             tsrDataMerged = list(),
             tsrCounts = data.frame(),
             consensusTSRs = data.frame()
             ),
         )
