################################################################################
#' tagCountTSS
#' @description Returns a matrix [a, h] where a = the number of unique TSSs
#' and h = the # of tags observed at that position
#'
#' @import BiocGenerics
#' @import GenomicRanges
#' @importFrom utils write.table
#'
#' @keywords internal


tagCountTSS <- function(y, outfname="TSS.txt", writeDF=FALSE) {
    x <- S4Vectors::split(y,seqnames(y))
    n.seq <- length(x)

    my.matrix <- NULL
    for (i in 1:n.seq) {
#VB Note: Print a progress note on every 20th sequence; 20 should be a parameter
        if (i%%20 == 0) {
            message("... tagCountTSS running with sequence ", i,
                " of ", n.seq, " for TSS set ", outfname, "\n")
        }
        this.seq <- as.character(x[[i]]@seqnames@values[1])

        #starting with the plus strand:
        tss.vec <- start(x[[i]][strand(x[[i]]) == "+"])
        if (length(tss.vec) > 3) {	#stop if there are nearly no tags
            my.TSSs <- unique(tss.vec)
            my.matrix.p <- matrix(NA, nrow=(length(my.TSSs)), ncol=4)

            this.TSS <- tss.vec[1]
            n.TSSs <- 1
            k <- 0
            for (j in 2:length(tss.vec)) {
                if (tss.vec[j] == this.TSS) {
                    n.TSSs <- n.TSSs + 1
                }
                else {
                    k <- k + 1
                    my.matrix.p[k,] <- c(this.seq, this.TSS, "+", n.TSSs)
                    this.TSS <- tss.vec[j]
                    n.TSSs <- 1
                }
            }
            k <- k + 1
            my.matrix.p[k,] <- c(this.seq, this.TSS, "+", n.TSSs)
# ... adding the plus strand matrix of this.seq to the overall matrix:
            my.matrix <- rbind(my.matrix,my.matrix.p)
        }

        #now for the minus strand:
        tss.vec <- start(x[[i]][strand(x[[i]]) == "-"])
        if (length(tss.vec) > 3) {
# ... no point continuing when there are almost no TSS tags
            my.TSSs <- unique(tss.vec)
            my.matrix.m <- matrix(NA, nrow=(length(my.TSSs)), ncol=4)

            this.TSS <- tss.vec[1]
            n.TSSs <- 1
            k <- 0
            for (j in 2:length(tss.vec)) {
                if (tss.vec[j] == this.TSS) {
                    n.TSSs <- n.TSSs + 1
                }
                else {
                    k <- k + 1
                    my.matrix.m[k,] <- c(this.seq, this.TSS, "-", n.TSSs)
                    this.TSS <- tss.vec[j]
                    n.TSSs <- 1
                }
            }
            k <- k + 1
            my.matrix.m[k,] <- c(this.seq, this.TSS, "-", n.TSSs)
# ... adding the minus strand matrix of this.seq to the overall matrix:
            my.matrix <- rbind(my.matrix,my.matrix.m)
        }
    }
    colnames(my.matrix) <- c("seq","TSS","strand","nTSSs")
    my.df <- as.data.frame(my.matrix)
    my.df$seq <- as.character(my.df$seq)
    my.df$TSS <- as.numeric(as.character(my.df$TSS))
    my.df$strand <- as.character(my.df$strand)
    my.df$nTSSs <- as.numeric(as.character(my.df$nTSSs))

    if (writeDF==TRUE) {
        write.table(my.df, outfname, quote=FALSE, col.names=TRUE,
                    row.names=FALSE, sep="\t")
        message("\nThe TSS dataset has been written to file ", outfname,
                "\nin your working directory.")
    }

    return(my.df)
}


################################################################################
#' @title tsrCluster
#' @description Partitions, then clusters tss data by sequence.
#'
#' @keywords internal
#'
#' @return A list of TSRs from the data frame generated by
#' \code{\link{tagCountTSS}}
#' @export


tsrCluster <- function(x, minNbrTSSs=3, minDist=20) {
    tss.df <- x
    uni.seq <- unique(tss.df[,1])
    n.seq <- length(uni.seq)
    overall.list <- vector(mode="list", length=n.seq)

    for (l in 1:n.seq) { #by sequence
        this.tss <- subset(tss.df, seq==uni.seq[l])
        sTSS <- subset(this.tss, this.tss$nTSSs>=minNbrTSSs)

        #... clustering TSS on the plus strand:

        sTSS.p <- subset(sTSS, strand=="+")
        sTSS.p <- as.matrix(sTSS.p)
        my.len <- nrow(sTSS.p)
        if (my.len == 0) { # ... create an empty list tss.list.p
            tss.list.p <- vector(mode="list")
        }
        else if (my.len == 1) {
            tss.list.p <- vector(mode="list")
            my.tss <- as.numeric(sTSS.p[1,2])
            my.count <- as.numeric(sTSS.p[1,4])
            combined.tss <- rbind(my.tss, my.count)
            rownames(combined.tss) <- c("coordinate","count")
            (colnames(combined.tss) <- 1:ncol(combined.tss))
            tss.list.p[[1]] <- combined.tss
        }
        else {
            tss.list.p <- vector(mode="list")
            my.tss <- as.numeric(sTSS.p[1,2])
            my.count <- as.numeric(sTSS.p[1,4])
            j <- 0
            for (i in 1:(my.len-1)) {
                tss.1 <- as.numeric(sTSS.p[i,2])
                tss.1.count <- as.numeric(sTSS.p[i,4])
                tss.2 <- as.numeric(sTSS.p[i+1,2])
                tss.2.count <- as.numeric(sTSS.p[i+1,4])
                tss.dist <- abs(tss.2-tss.1)
                if (tss.dist < minDist) {
                    my.tss <- c(my.tss,tss.2)
                    my.count <- c(my.count, tss.2.count)
                    if (i == my.len-1) {	# wrapping up the last TSR
                        j <- j + 1
                        combined.tss <- rbind(my.tss, my.count)
                        rownames(combined.tss) <- c("coordinate","count")
                        (colnames(combined.tss) <- 1:ncol(combined.tss))
                        tss.list.p[[j]] <- combined.tss
                    }
                    next
                }
                else {
                    j <- j + 1
                    combined.tss <- rbind(my.tss, my.count)
                    rownames(combined.tss) <- c("coordinate","count")
                    (colnames(combined.tss) <- 1:ncol(combined.tss))
                    tss.list.p[[j]] <- combined.tss
                    my.tss <- tss.2
                    my.count <- tss.2.count
                }
            }
        }
        if (my.len > 0) {
            names.len <- length(tss.list.p)
            names.vec <- vector(mode="character",length=names.len)
            for (k in 1:names.len) {
                names.vec[k] <- paste("tsr", k, sep="")
            }
            names(tss.list.p) <- names.vec
        }

        #... clustering TSS on the minus strand:

        sTSS.m <- subset(sTSS, strand=="-")
        sTSS.m <- as.matrix(sTSS.m)
        my.len <- nrow(sTSS.m)
        if (my.len == 0) { # ... create an empty list tss.list.m
            tss.list.m <- vector(mode="list")
        }
        else if (my.len == 1) {
            tss.list.m <- vector(mode="list")
            my.tss <- as.numeric(sTSS.m[1,2])
            my.count <- as.numeric(sTSS.m[1,4])
            combined.tss <- rbind(my.tss, my.count)
            rownames(combined.tss) <- c("coordinate","count")
            (colnames(combined.tss) <- 1:ncol(combined.tss))
            tss.list.m[[1]] <- combined.tss
        }
        else {
            tss.list.m <- vector(mode="list")
            my.tss <- as.numeric(sTSS.m[1,2])
            my.count <- as.numeric(sTSS.m[1,4])
            j <- 0
            for (i in 1:(my.len-1)) {
                tss.1 <- as.numeric(sTSS.m[i,2])
                tss.1.count <- as.numeric(sTSS.m[i,4])
                tss.2 <- as.numeric(sTSS.m[i+1,2])
                tss.2.count <- as.numeric(sTSS.m[i+1,4])
                tss.dist <- abs(tss.2-tss.1)
                if (tss.dist < minDist) {
                    my.tss <- c(my.tss,tss.2)
                    my.count <- c(my.count, tss.2.count)
                    if (i == my.len-1) {	# wrapping up the last TSR
                        j <- j + 1
                        combined.tss <- rbind(my.tss, my.count)
                        rownames(combined.tss) <- c("coordinate","count")
                        (colnames(combined.tss) <- 1:ncol(combined.tss))
                        tss.list.m[[j]] <- combined.tss
                    }
                    next
                }
                else {
                    j <- j + 1
                    combined.tss <- rbind(my.tss, my.count)
                    rownames(combined.tss) <- c("coordinate","count")
                    (colnames(combined.tss) <- 1:ncol(combined.tss))
                    tss.list.m[[j]] <- combined.tss
                    my.tss <- tss.2
                    my.count <- tss.2.count
                }
            }
        }
        if (my.len > 0) {
            names.len <- length(tss.list.m)
            names.vec <- vector(mode="character",length=names.len)
            for (k in 1:names.len) {
                names.vec[k] <- paste("tsr", k, sep="")
            }
            names(tss.list.m) <- names.vec
        }
        tss.list <- list(plus=tss.list.p, minus=tss.list.m)
        overall.list[[l]] <- tss.list

    }	#end of by sequence for-loop

    names(overall.list) <- uni.seq
    return(overall.list)
}
